---
# This is the top-level playbook that defines our entire infrastructure.

- hosts: fedora-workstation
#  user: tenfourty
#  sudo: True
  gather_facts: True
#  vars_files:
#    - vars/defaults.yml
#    - vars/{{ 'testing' if testing is defined else 'user' }}.yml

  roles:
    - workstation

