---
infra_repo: "https://github.com/tenfourty/tenfourty-infrastructure-mgmt.git"
infra_repo_accept_hostkey: no
infra_repo_local_destination: "/share/homes/admin/tenfourty-infrastructure-mgmt"

link_files:
  #- ["/root/.bash_logout", "files/qnap/dotfiles/.bash_logout"]
  #- ["/root/.bash_profile", "files/qnap/dotfiles/.bash_profile"]
  #- ["/root/.bashrc", "files/qnap/dotfiles/.bashrc"]
  #- ["/root/.profile", "files/qnap/dotfiles/.profile"]
  #- ["/root/.vimrc", "files/qnap/dotfiles/.vimrc"]
  #- ["/root/.gitconfig", "files/qnap/dotfiles/.gitconfig"]
  # - ["/share/QDownload/repos/.htaccess", "files/qnap/repos/.htaccess"]
  # - ["/share/QDownload/repos/rsyncrepos.sh", "files/qnap/repos/rsyncrepos.sh"]
  # - ["/share/QDownload/kickstart/.htaccess", "files/qnap/kickstart/.htaccess"]
  # - ["/share/QDownload/kickstart/ks_centos_6_i386_rescue.cfg", "files/qnap/kickstart/ks_centos_6_i386_rescue.cfg"]
  # - ["/share/QDownload/kickstart/ks_centos_6_x86_64_rescue.cfg", "files/qnap/kickstart/ks_centos_6_x86_64_rescue.cfg"]
  # - ["/share/QDownload/kickstart/ks_centos_7_rescue.cfg", "files/qnap/kickstart/ks_centos_7_rescue.cfg"]
  # - ["/share/QDownload/kickstart/ks_centos_7_openshift_aio.cfg", "files/qnap/kickstart/ks_centos_7_openshift_aio.cfg"]
  # - ["/share/QDownload/kickstart/ks_nuc_01.cfg", "files/qnap/kickstart/ks_nuc_01.cfg"]
  # - ["/share/QDownload/tftp/pxelinux/pxelinux.cfg/clonezilla", "files/qnap/pxelinux/pxelinux.cfg/clonezilla"]
  # - ["/share/QDownload/tftp/pxelinux/pxelinux.cfg/default", "files/qnap/pxelinux/pxelinux.cfg/default"]
  # - ["/share/QDownload/tftp/pxelinux/pxelinux.cfg/ocswp.png", "files/qnap/pxelinux/pxelinux.cfg/ocswp.png"]
  # - ["/share/QDownload/tftp/pxelinux/pxelinux.cfg/tools", "files/qnap/pxelinux/pxelinux.cfg/tools"]
  # - ["/share/QDownload/tftp/pxelinux/pxelinux.cfg/x86_64_Servers", "files/qnap/pxelinux/pxelinux.cfg/x86_64_Servers"]
  # - ["/share/QDownload/tftp/pxelinux/pxelinux.cfg/x86_Servers", "files/qnap/pxelinux/pxelinux.cfg/x86_Servers"]
  - ["/share/Container/docker-compose.yml", "files/qnap/docker-compose/docker-compose.yml"]
  - ["/share/Container/transmissionDockerEnv", "files/qnap/docker-compose/transmissionDockerEnv"]

files_with_secrets:
  - ["files/qnap/docker-compose/transmissionDockerEnvSecrets.j2", "/share/Container/transmissionDockerEnvSecrets"]
