---
- name: Ensure tenfourty_infra repository is cloned locally.
  git:
    executable: "/opt/bin/git"
    repo: "{{ infra_repo }}"
    dest: "{{ infra_repo_local_destination }}"
    accept_hostkey: "{{ infra_repo_accept_hostkey }}"
  become: no

- name: Run the script to install the autorun.sh script
  shell: "{{ infra_repo_local_destination|quote }}/files/qnap/autorun/installautorun.sh"
  args:
    chdir: "{{ infra_repo_local_destination }}/files/qnap/autorun/"

- name: Getting file info on the files we want to link to this repo
  stat:
    path: "{{ item.0 }}"
  loop: "{{ link_files }}"
  register: files
  
- debug:
    var: files
    verbosity: 3

- name: Backup files that are not links
  command: "mv {{ item.item.0 }} {{ item.item.0 }}.bak"
  loop: "{{ files.results }}"
  when: item.stat.exists and item.stat.islnk is defined and item.stat.islnk == false

- name: Ensure all configured files are linked to.
  file:
    src: "{{ infra_repo_local_destination }}/{{ item.1 }}"
    path: "{{ item.0 }}"
    state: link
    force: yes
  loop: "{{ link_files }}"

- name: Secrets Files
  template:
    src: "{{ item.0 }}"
    dest: "{{ item.1 }}"
  loop: "{{ files_with_secrets }}"
