version: '3.4'
services:

  watchtower:
    container_name: watchtower
    restart: always
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 0 6 * * *" --cleanup
    env_file:
      - ./qnapdockerfiles/watchtower/secrets.env
    environment:
      - WATCHTOWER_NOTIFICATIONS_LEVEL=info
      - WATCHTOWER_NOTIFICATIONS=slack
      - WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER=watchtower-qnap

# docker run -v /var/run/docker.sock:/var/run/docker.sock -d --restart=always --name docker-sock-proxy docksal/socat
  dockersocket:
    container_name: dockersocket
    restart: always
#    image: tecnativa/docker-socket-proxy
    image: docksal/socat
    depends_on:
      - watchtower
    privileged: true
    networks:
      - private
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#    environment:
#      - CONTAINERS=1
#      - NETWORKS=1
#      - SERVICES=1
#      - SWARM=1
#      - TASKS=1

  traefik:
    hostname: traefik
    image: traefik:latest
    container_name: traefik
    restart: always
    depends_on:
      - watchtower
      - dockersocket
    domainname: home.${DOMAINNAME}
    networks:
      - private
      - traefik_proxy
    ports:
      - 80:80
      - 443:443
      - 8480:8080
    env_file:
      - ./qnapdockerfiles/traefik/secrets.env
    volumes:
      - /share/Container/container-data/traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.frontend.rule=Host:home.${DOMAINNAME}; PathPrefixStrip: /traefik"
      - "traefik.port=8080"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
#      - "traefik.frontend.headers.frameDeny=true"
      - "traefik.frontend.auth.basic.usersFile=/etc/traefik/.htpasswd"

  mariadb:
    image: "linuxserver/mariadb"
    container_name: "mariadb"
    depends_on:
      - watchtower
    hostname: mariadb
    volumes:
        - /share/Container/container-data/mariadb:/config
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
        mode: host
    restart: always
    env_file:
      - ./qnapdockerfiles/mariadb/secrets.env
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Paris
    networks:
      - mariadb

# WebUI for MariaDB
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - watchtower
      - mariadb
      - traefik
    restart: always
    ports:
      - 8280:80
    environment:
      - PMA_HOST=oga2
    hostname: phpmyadmin
    domainname: ${DOMAINNAME}

# NextCloud Your Own Cloud Storage

  nextcloud_redis:
    image: redis:alpine
    container_name: nextcloud_redis
    restart: always
    depends_on:
      - watchtower
    networks:
      - nextcloud_app

  nextcloud_app:
    build: ./qnapdockerfiles/nextcloud/app
    container_name: nextcloud_app
    restart: always
    depends_on:
      - watchtower
      - mariadb
      - nextcloud_redis
    volumes:
      - /share/NextCloud:/var/www/html
    environment:
      - PUID=0
      - PGID=0
    networks:
      - nextcloud_app
      - mariadb

  nextcloud_web:
    build: ./qnapdockerfiles/nextcloud/web
    container_name: nextcloud_web
    restart: always
    depends_on:
      - watchtower
      - mariadb
      - nextcloud_app
      - traefik
    expose:
      - 80
    links:
      - nextcloud_app
    volumes:
      - /share/NextCloud:/var/www/html:ro
    networks:
      - nextcloud_app
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=nextcloud_web"
      - "traefik.frontend.rule=Host:nextcloud.${DOMAINNAME}"
      - "traefik.port=80"
      - "traefik.protocol=https"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
#     - "traefik.frontend.headers.frameDeny=true"
      - "traefik.frontend.passHostHeader=true"

  nextcloud_cron:
    build: ./qnapdockerfiles/nextcloud/app
    container_name: nextcloud_cron
    restart: always
    volumes:
      - /share/NextCloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - watchtower
      - mariadb
      - nextcloud_redis

#  nextcloud:
#    container_name: nextcloud
#    restart: always
#    image: nextcloud
#    depends_on:
#      - watchtower
#      - mariadb
#      - traefik
#    links:
#      - mariadb:mariadb
#    volumes:
#      - /share/NextCloud/:/var/www/html
#    environment:
#      - PUID=0
#      - PGID=0
##    hostname: nextcloud
##    domainname: ${DOMAINNAME}
##    mac_address: 8E:A5:C8:01:E6:FD
##    dns: ${LOCALDNS}
#    ports:
#      - 9190:443
#    networks:
#      - qnet-dhcp
#      - traefik_proxy
#    labels:
#      - "traefik.enable=true"
#      - "traefik.backend=nextcloud"
#      - "traefik.frontend.rule=Host:nextcloud.${DOMAINNAME}"
#      - "traefik.port=443"
#      - "traefik.protocol=https"
#      - "traefik.docker.network=traefik_proxy"
#      - "traefik.frontend.headers.SSLRedirect=true"
#      - "traefik.frontend.headers.STSSeconds=315360000"
#      - "traefik.frontend.headers.browserXSSFilter=true"
#      - "traefik.frontend.headers.contentTypeNosniff=true"
#      - "traefik.frontend.headers.forceSTSHeader=true"
#      - "traefik.frontend.headers.STSIncludeSubdomains=true"
#      - "traefik.frontend.headers.STSPreload=true"
# #     - "traefik.frontend.headers.frameDeny=true"
#      - "traefik.frontend.passHostHeader=true"

  transmission:
    container_name: transmission
    image: haugene/transmission-openvpn:latest
    restart: always
    depends_on:
      - watchtower
      - traefik
#    domainname: ${DOMAINNAME}
#    hostname: transmission
#    mac_address: 72:8E:00:32:D3:49
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    env_file:
      - ./qnapdockerfiles/transmission/config.env
      - ./qnapdockerfiles/transmission/secrets.env
    volumes:
      - /share/Container/container-data/transmission/:/config:rw
      - /share/QDownload/transmission/:/data:rw
      - /share/QDownload/transmission/:/downloads:rw
      - /etc/localtime:/etc/localtime:ro
#    dns: ${LOCALDNS}
    networks:
#      - qnet-dhcp
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=transmission-vpn"
      - "traefik.frontend.rule=Host:home.${DOMAINNAME}; PathPrefix: /transmission"
      - "traefik.port=9091"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"

  sabnzbd:
    container_name: sabnzbd
    image: linuxserver/sabnzbd:latest
    restart: always
    depends_on:
      - watchtower
      - traefik
    ports:
       - 8380:8080
#       - 9390:9090
    environment:
      - TZ=Europe/Paris
      - PUID=0 
      - PGID=0
    volumes:
      - /share/Container/container-data/sabnzbd:/config:rw
      - /share/QDownload/sabnzbd/incomplete-downloads:/incomplete-downloads:rw
      - /share/QDownload/transmission/completed:/downloads:rw
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=sabnzbd"
      - "traefik.frontend.rule=Host:home.${DOMAINNAME}; PathPrefix: /sabnzbd"
      - "traefik.port=8080"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.whiteList.sourceRange=${LOCALNETWORKS}"

  couchpotato:
    container_name: couchpotato
    image: linuxserver/couchpotato:latest
    restart: always
    depends_on:
      - watchtower
      - traefik
      - transmission
      - sabnzbd
    environment:
      - TZ=Europe/Paris
      - PUID=0
      - PGID=0
    volumes:
      - /share/QMultimedia/Video/Movies:/movies:rw
      - /share/Container/container-data/couchpotato/:/config:rw
      - /share/QDownload/transmission/:/downloads:rw
    ports:
      - 5050:5050
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=couchpotato"
      - "traefik.frontend.rule=Host:home.${DOMAINNAME}; PathPrefix: /couchpotato"
      - "traefik.port=5050"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.whiteList.sourceRange=${LOCALNETWORKS}"

  sickchill:
    container_name: sickchill
    image: linuxserver/sickrage:latest
    restart: always
    depends_on:
      - watchtower
      - traefik
      - transmission
      - sabnzbd
    ports:
      - 8481:8081
    environment:
      - TZ=Europe/Paris
      - PUID=0
      - PGID=0
    volumes:
      - /share/QMultimedia/Video/TV:/tv:rw
      - /share/Container/container-data/sickrage/:/config:rw
      - /share/QDownload/transmission/:/downloads:rw
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=sickchill"
      - "traefik.frontend.rule=Host:home.${DOMAINNAME}; PathPrefix: /sickchill"
      - "traefik.port=8081"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.whiteList.sourceRange=${LOCALNETWORKS}"

  plex:
    container_name: plex
    image: plexinc/pms-docker:plexpass
    restart: always
    depends_on:
      - watchtower
      - traefik
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1901:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32414:32414/udp
    environment:
      - TZ=Europe/Paris
      - PLEX_UID=0
      - PLEX_GID=0
      - ADVERTISE_IP=https://plex.tenfourty.com:443/
    volumes:
      - /share/Container/container-data/plex/config:/config:rw
      - /share/QMultimedia:/data:rw
      - /share/Container/container-data/plex/transcode:/transcode:rw
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=plex"
      - "traefik.frontend.rule=Host:plex.tenfourty.com"
      - "traefik.port=32400"
#      - "traefik.protocol=http"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
#      - "traefik.frontend.headers.STSSeconds=315360000"
#      - "traefik.frontend.headers.browserXSSFilter=true"
#      - "traefik.frontend.headers.contentTypeNosniff=true"
#      - "traefik.frontend.headers.forceSTSHeader=true"
#      - "traefik.frontend.headers.STSIncludeSubdomains=true"
#      - "traefik.frontend.headers.STSPreload=true"
#      - "traefik.frontend.headers.frameDeny=true"
#      - "traefik.frontend.passHostHeader=true"


  tautulli:
    container_name: tautulli
    image: linuxserver/tautulli
    restart: always
    depends_on:
      - watchtower
      - traefik
      - plex
    volumes:
      - /share/Container/container-data/tautulli/config:/config
      - /share/Container/container-data/tautulli/logs:/logs:ro
    ports:
      - 8281:8181
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Paris
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=tautulli"
      - "traefik.frontend.rule=Host:home.${DOMAINNAME}; PathPrefix: /tautulli"
      - "traefik.port=8181"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.passHostHeader=true"

  ombi:
    container_name: ombi
    image: linuxserver/ombi
    restart: always
    depends_on:
      - watchtower
      - traefik
      - plex
      - sickchill
      - couchpotato
    volumes:
      - /share/Container/container-data/ombi:/config
    ports:
      - 3579:3579
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Paris
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=ombi"
      - "traefik.frontend.rule=Host:home.${DOMAINNAME}; PathPrefix: /ombi"
      - "traefik.port=3579"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.passHostHeader=true"

  organizr:
    container_name: organizr
    image: organizrtools/organizr-v2:php-fpm
    restart: always
    depends_on:
      - watchtower
      - traefik
      - mariadb
      - phpmyadmin
#      - nextcloud
      - couchpotato
      - sickchill
      - transmission
      - sabnzbd
      - ombi
      - plex
      - tautulli
    volumes:
      - /share/Container/container-data/organizr:/config
    ports:
      - 8282:80
    environment:
      - PUID=1001
      - PGID=100
      - TZ=Europe/Paris
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=organizr"
      - "traefik.frontend.rule=Host:home.${DOMAINNAME}"  
      - "traefik.port=80"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"

# https://qnap-dev.github.io/container-station-api/index.html
networks:

# docker network create -d qnet --ipam-driver=qnet --ipam-opt=iface=bond0 qnet-dhcp
#  qnet-dhcp:
#    external:
#      name: qnet-dhcp

  private:
    external: true
    driver_opts:
      encrypted: 1

  mariadb:
    external: true
    driver_opts:
      encrypted: 1

  nextcloud_app:
    external: true
    driver_opts:
      encrypted: 1

# docker network create traefik_proxy
  traefik_proxy:
    external: true
    driver_opts:
      encrypted: 1

