version: '2.4'
services:
#  qnet_dhcp:
#    image: alpine
#    command: ifconfig eth0
#    networks:
#      - qnet-dhcp

#  transmission:
#    container_name: transmission
#    image: haugene/transmission-openvpn:latest
#    restart: always
#    cpu_shares: 512
#    mem_limit: 256m
#    cap_add:
#      - NET_ADMIN
#    devices:
#      - "/dev/net/tun"
#    env_file:
#      - transmissionDockerEnv
#      - transmissionDockerEnvSecrets
#    volumes:
#      - /share/Container/container-data/transmission/:/config:rw
#      - /share/QDownload/transmission/:/data:rw
#      - /share/QDownload/transmission/:/downloads:rw
#      - /etc/localtime:/etc/localtime:ro
##      - /etc/resolv.dnsmasq:/etc/resolv.conf:ro
#    dns: 10.10.10.10
#    networks:
#      qnet-static-trusted:
#        ipv4_address: 10.10.10.251
#    network_mode: "host"
#    logging:
#      driver: syslog
#      options:
#        syslog-address: "tcp://192.168.1.1:514"
#        tag: transmission
#        syslog-format: rfc5424micro

#  couchpotato:
#    container_name: couchpotato
#    depends_on:
#      - transmission
#    image: linuxserver/couchpotato:latest
#    restart: always
#    cpu_shares: 1024
#    mem_limit: 256m
#    environment:
#      - TZ=Europe/Paris
#      - PUID=0
#      - PGID=0
#    volumes:
#      - /share/QMultimedia/Video/Movies:/movies:rw
#      - /share/Container/container-data/couchpotato/:/config:rw
#      - /share/QDownload/transmission/:/downloads:rw
#    ports:
#      - "5050:5050"
#    dns: 10.10.10.10
#    network_mode: "host"
#    logging:
#      driver: syslog
#      options:
#        syslog-address: "tcp://192.168.1.1:514"
#        tag: couchpotato
#        syslog-format: rfc5424micro

#  sickrage:
#    container_name: sickrage
#    depends_on:
#      - transmission
#    image: linuxserver/sickrage:latest
#    restart: always
#    cpu_shares: 1024
#    mem_limit: 256m
#    environment:
#      - TZ=Europe/Paris
#      - PUID=0
#      - PGID=0
#    volumes:
#      - /share/QMultimedia/Video/TV:/tv:rw
#      - /share/Container/container-data/sickrage/:/config:rw
#      - /share/QDownload/transmission/:/downloads:rw
 #   ports:
 #     - "7073:8081"
#    dns: 10.10.10.10
#    networks:
#      qnet-static-trusted:
#        ipv4_address: 10.10.10.252
#    logging:
#      driver: syslog
#      options:
#        syslog-address: "tcp://192.168.1.1:514"
#        tag: sickrage
#        syslog-format: rfc5424micro

  plex:
    container_name: plex
    image: plexinc/pms-docker:plexpass
    restart: always
    cpu_shares: 4096
    mem_limit: 3g
    environment:
      - TZ=Europe/Paris
      - PLEX_UID=0
      - PLEX_GID=0
    volumes:
      - /share/Container/container-data/plex/config:/config:rw
      - /share/QMultimedia:/data:rw
      - /share/Container/container-data/plex/transcode:/transcode:rw
    dns: 10.10.10.10
    networks:
      qnet-static:
        ipv4_address: 10.10.10.250
#    logging:
#      driver: syslog
#      options:
#        syslog-address: "tcp://192.168.1.1:514"
#        tag: plex
#        syslog-format: rfc5424micro

  unifi-mongo:
    image: mongo:3.4
    dns: 10.10.10.10
    networks:
      qnet-static:
        ipv4_address: 10.10.10.253
    restart: always
    volumes:
      - /share/Container/container-data/unifi/db:/data/db:rw
  
  unifi-controller:
    image: "jacobalberty/unifi:latest"
    depends_on:
      - unifi-mongo
    init: true
    dns: 10.10.10.10
    networks:
      qnet-static:
        ipv4_address: 10.10.10.254
    restart: always
    volumes:
      - /share/Container/container-data/unifi/data:/unifi/data
      - /share/Container/container-data/unifi/log:/unifi/log
      - /share/Container/container-data/unifi/cert:/unifi/cert
      - /share/Container/container-data/unifi/init:/unifi/init.d
    environment:
      DB_URI: mongodb://mongo/unifi
      STATDB_URI: mongodb://mongo/unifi_stat
      DB_NAME: unifi
    ports:
      - "8080:8080"
      - "8443:8443"
      - "3478:3478/udp"
      - "10001:10001/udp"

  unifi-logs:
    image: bash
    depends_on:
      - unifi-controller
    command: bash -c 'tail -f /unifi/log/*'
    restart: always
    volumes:
      - /share/Container/container-data/unifi/log:/unifi/log

networks:
#  qnet-dhcp:
#    driver: qnet
#    ipam:
#      driver: qnet
#      options:
#        iface: "bond0"

  qnet-static:
    driver: qnet
    ipam:
      driver: qnet
      options:
        iface: "bond0"
      config:
        - subnet: 10.10.10.0/24
          gateway: 10.10.10.1

#  unifi:
#    driver: qnet
#    ipam:
#      driver: qnet
#      options:
#        iface: "bond0"
