version: '2.4'
services:

  transmission:
    container_name: transmission
    image: haugene/transmission-openvpn:latest
    restart: always
    cpu_shares: 512
    mem_limit: 256m
    domainname: tenfourty.com
    hostname: transmission
    mac_address: 72:8E:00:32:D3:49
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    env_file:
      - transmissionDockerEnv
      - transmissionDockerEnvSecrets
    volumes:
      - /share/Container/container-data/transmission/:/config:rw
      - /share/QDownload/transmission/:/data:rw
      - /share/QDownload/transmission/:/downloads:rw
      - /etc/localtime:/etc/localtime:ro
#      - /etc/resolv.dnsmasq:/etc/resolv.conf:ro
    dns: 10.10.10.10
    networks:
      - qnet-dhcp

  couchpotato:
    container_name: couchpotato
    depends_on:
      - transmission
    image: linuxserver/couchpotato:latest
    restart: always
    cpu_shares: 1024
    mem_limit: 256m
    domainname: tenfourty.com
    hostname: couchpotato
    mac_address: AA:6D:1B:43:C9:9C
    environment:
      - TZ=Europe/Paris
      - PUID=0
      - PGID=0
    volumes:
      - /share/QMultimedia/Video/Movies:/movies:rw
      - /share/Container/container-data/couchpotato/:/config:rw
      - /share/QDownload/transmission/:/downloads:rw
#    ports:
#      - "5050:5050"
    dns: 10.10.10.10
    networks:
      - qnet-dhcp
#    network_mode: "host"

  sickchill:
    container_name: sickchill
    depends_on:
      - transmission
    image: linuxserver/sickrage:latest
    restart: always
    cpu_shares: 1024
    mem_limit: 256m
    domainname: tenfourty.com
    hostname: sickchill
    mac_address: 56:CE:D9:89:80:B8
    environment:
      - TZ=Europe/Paris
      - PUID=0
      - PGID=0
    volumes:
      - /share/QMultimedia/Video/TV:/tv:rw
      - /share/Container/container-data/sickrage/:/config:rw
      - /share/QDownload/transmission/:/downloads:rw
    dns: 10.10.10.10
    networks:
      - qnet-dhcp

  plex:
    container_name: plex
    image: plexinc/pms-docker:plexpass
    restart: always
    cpu_shares: 4096
    mem_limit: 3g
    domainname: tenfourty.com
    hostname: plex
    mac_address: 02:42:bf:05:48:f3
    environment:
      - TZ=Europe/Paris
      - PLEX_UID=0
      - PLEX_GID=0
    volumes:
      - /share/Container/container-data/plex/config:/config:rw
      - /share/QMultimedia:/data:rw
      - /share/Container/container-data/plex/transcode:/transcode:rw
    dns: 10.10.10.10
    networks:
      - qnet-dhcp

#  unifi-mongo:
#    container_name: unifi-mongo
#    image: mongo:3.4
#    cpu_shares: 4096
#    mem_limit: 2g
#    domainname: tenfourty.com
#    hostname: unifi-mongo
#    dns: 10.10.10.10
#    networks:
#      qnet-static:
#        ipv4_address: 10.10.10.253
#    restart: always
#    volumes:
#      - /share/Container/container-data/unifi/db:/data/db:rw
  
#  unifi-controller:
#    container_name: unifi-controller
#    image: "jacobalberty/unifi:stable"
##    depends_on:
##      - unifi-mongo
#    init: true
#    cpu_shares: 4096
#    mem_limit: 4g
#    domainname: tenfourty.com
#    hostname: unifi
#    dns: 10.10.10.10
#    networks:
#      qnet-static:
#        ipv4_address: 10.10.10.254
#    restart: always
#    volumes:
#      - /share/Container/container-data/unifi-stable:/unifi
##      - /share/Container/container-data/unifi/data:/unifi/data
##      - /share/Container/container-data/unifi/log:/unifi/log
##      - /share/Container/container-data/unifi/cert:/unifi/cert
##      - /share/Container/container-data/unifi/init:/unifi/init.d
#      - /share/Container/container-data/unifi-stable/var/run/unifi:/var/run/unifi
#    environment:
##      - DB_URI="mongodb://unifi-mongo/unifi"
##      - STATDB_URI="mongodb://unifi-mongo/unifi_stat"
##      - DB_NAME=unifi
#      - RUNAS_UID0=true
##      - UNIFI_UID=999
##      - UNIFI_GID=999
#      - TZ=Europe/Paris
#      - JVM_MAX_THREAD_STACK_SIZE=1280k

#  unifi-logs:
#    container_name: unifi-logs
#    image: bash
#    depends_on:
#      - unifi-controller
#    command: bash -c 'tail -f /unifi/log/*'
#    restart: always
#    volumes:
#      - /share/Container/container-data/unifi-stable/log:/unifi/log

#  unms:
#    container_name: unms
#    image: oznu/unms:latest
#    restart: always
#    cpu_shares: 4096
#    mem_limit: 4g
#    domainname: tenfourty.com
#    hostname: unms
#    dns: 10.10.10.10
#    cap_add:
#      - NET_ADMIN
#    networks:
#      qnet-static:
#        ipv4_address: 10.10.10.253
#    environment:
#      - TZ=Europe/Paris
#    volumes:
#      - /share/Container/container-data/unms:/config

networks:
  qnet-dhcp:
    driver: qnet
    ipam:
      driver: qnet
      options:
        iface: "bond0"

#  qnet-static:
#    driver: qnet
#    ipam:
#      driver: qnet
#      options:
#        iface: "bond0"
#      config:
#        - subnet: 10.10.10.0/24
#          gateway: 10.10.10.1

#  unifi:
#    driver: qnet
#    ipam:
#      driver: qnet
#      options:
#        iface: "bond0"


#    logging:
#      driver: syslog
#      options:
#        syslog-address: "tcp://192.168.1.1:514"
#        tag: couchpotato
#        syslog-format: rfc5424micro
